### ISSUE TITLE
Release day checklist

### ISSUE THREAD

**Issue by zkat** [BanchanArt/banchan#523]
Stuff we need to do when it's time to release:

* [x] Scale fly prod app to 2 `shared-cpu-4x` machines @ 1GB
* [x] Scale fly db app to 2  `shared-cpu-4x` machines @ 1GB
* [x] Switch to paid Sentry plan
* [x] Upgrade SendGrid plan
* [x] #626
* [x] mark blog post as published
* [ ] tag a Banchan release and deploy it
* [x] Poke around and make sure everything looks good
* [x] Remove `BASIC_AUTH_{USERNAME,PASSWORD}` secrets from prod
* [x] Post social media announcements
  * [x] Twitter (bleh), boost from personal acct
  * [x] Mastodon.art (maybe ping Curator?), boost from personal accts
  * [ ] Instagram?
  * [x] `@everyone` on Discord `#announcements`
